import streamlit as st




def show_home_page():
    st.image("logo.png", width=250)
    
    st.title('Welcome to CodeCraft GPT')

    st.write('CodeCraft AI is an all-in-one platform that revolutionizes the coding experience for developers.')
    
    st.subheader('What CodeCraft GPT Offers:')
    st.markdown("""
    - 👉 Intelligent suggestions and automated refactoring
    - 👨‍🏫 Get feedback on coding style
    - 🧪 Test case generation for code snippets
    - 🔄 Code translation between programming languages
    """)

    st.subheader('How to Use CodeCraft GPT')
    st.markdown("""
    1. Provide the code snippet you want to refactor. Wait for intelligent refinements and automated refactoring suggestions.
    2. Enter your code snippet and get feedback on suggested coding style. Receive feedback on coding style and improvement suggestions.
    3. Enter code snippet and get automatically generated test cases for the code snippet, functions, or classes.
    4. Share the source code you want to translate and it will be auto-translated to the target language.
    5. Input code snippet and get full autogenerated documentation.
    """)